name: deep_lungs
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  image_picker: ^1.2.2
  video_player: ^2.10.1
  google_fonts: ^6.2.1
  vibration: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  rename: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/splash_video.mp4

# ---------------------------------------------------
# (App Icon)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

# (Splash Screen)
flutter_native_splash:
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"